%YAML:1.0
---
grid_map:
    frame_id: "world"
    enable_virtual_wall: 0
    pose_type: 2
    odom_depth_timeout: 1.0
    resolution: 0.2
    local_update_range_x: 15.5
    local_update_range_y: 15.5
    local_update_range_z: 2.0
    obstacles_inflation: 0.1
    virtual_ceil: 3.0
    virtual_ground: -0.1

    virtual_wall_x_min: -20.0
    virtual_wall_x_max: 20.0
    virtual_wall_y_min: -20.0
    virtual_wall_y_max: 20.0
    virtual_wall_z_min: -0.1
    virtual_wall_z_max: 3
    virtual_wall_margin: 0.1
    virtual_wall_yaw: 0.0

    use_depth_filter: 1
    depth_filter_tolerance: 0.15
    depth_filter_maxdist: 15.0
    depth_filter_mindist: 0.1
    depth_filter_margin: 2
    k_depth_scaling_factor: 1000
    est_depth_scaling_factor: 1
    inverse_depth: 0
    skip_pixel: 2
    p_hit: 0.65
    p_miss: 0.35
    p_min: 0.12
    p_max: 0.90
    p_occ: 0.80
    fading_time: 10
    occ_interval: 0.032
    vis_interval: 0.125
    min_ray_length: 0.1
    max_ray_length: 4.5
    visualization_truncate_height: 1.9
    show_occ_time: 0
fsm:
    flight_type: 1
    thresh_replan_time: 1.0
    planning_horizon: 5.0
    emergency_time: 1.0
    realworld_experiment: 0
    fail_safe: 1
    ground_height_measurement: 0
manager: 
    max_vel: 1.5
    max_acc: 6.0
    polyTraj_piece_length: 1.5
    feasibility_tolerance: 0.05
    planning_horizon: 7.5
    use_multitopology_trajs: 0
optimization:
    constraint_points_perPiece: 5
    weight_obstacle: 10000.0
    weight_obstacle_soft: 5000.0
    weight_swarm: 10000.0
    weight_feasibility: 10000.0
    weight_sqrvariance: 10000.0
    weight_time: 10.0
    obstacle_clearance: 0.1
    obstacle_clearance_soft: 0.5
    swarm_clearance: 0.15000000000000002
    max_vel: 0.5
    max_acc: 6.0
    max_jer: 20.0