%YAML:1.0

d2slam:
    #inputs
    imu: 1         
    imu_topic: "/mavros/imu/data_raw"
    image0_topic: "/camera/infra1/image_rect_raw"
    image1_topic: "/camera/infra2/image_rect_raw"
    is_compressed_images: 0
    imu_freq: 200
    image_freq: 15
    frame_step: 3
    #Camera configuration
    camera_configuration: 0  #STEREO_PINHOLE = 0, STEREO_FISHEYE = 1, PINHOLE_DEPTH = 2, FOURCORNER_FISHEYE = 3
    num_of_cam: 2
    cam0_calib: "../../camera/d435_realsense/left_480x270.yaml"
    cam1_calib: "../../camera/d435_realsense/right_480x270.yaml"
    image_width: 480
    image_height: 270
    body_T_cam0: !!opencv-matrix
        rows: 4
        cols: 4
        dt: d
        data: [-0.03219517, 0.00488071, 0.99946968, 0.04700941,
            0.99918217, -0.02431851, 0.03230467, 0.02117146,
            0.02446328, 0.99969235, -0.00409378, 0.04328738,
            0.00000000, 0.00000000, 0.00000000, 1.00000000]
    body_T_cam1: !!opencv-matrix
        rows: 4
        cols: 4
        dt: d
        data: [-0.03226768, 0.00496599, 0.99946693, 0.04557953,
            0.99918751, -0.02399975, 0.03237790, 0.07096948,
            0.02414774, 0.99969963, -0.00418754, 0.04445992,
            0.00000000, 0.00000000, 0.00000000, 1.00000000]
    #estimation
    estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
    estimate_td: 0                      # online estimate time offset between camera and imu
    td: 0.001                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
    estimation_mode: 0 #0:single; 1:solve all; 2: distributed; 3:server
    double_counting_common_feature: 0
    min_inv_dep: 0.01 #100 meter away.
    min_measurements_per_keyframe: 10
    #optimization parameters
    max_solver_time: 0.04 # max solver itration time (ms), to guarantee real time
    max_num_iterations: 8   # max solver itrations, to guarantee real time
    consensus_max_steps: 1
    timout_wait_sync: 100
    rho_landmark: 1.0
    rho_frame_T: 100
    rho_frame_theta: 100
    relaxation_alpha: 0.
    consensus_sync_for_averaging: 0
    consensus_sync_to_start: 0 #Is sync on start of the solving..
    consensus_trigger_time_err_us: 100
    ceres_num_threads: 4
    freeze_disarm_pose: 0
    #depth fusing
    depth_far_thres: 3.0 # The max depth in frontend
    depth_near_thres: 0.3 
    fuse_dep: 0 #if fuse depth measurement
    max_depth_to_fuse: 5.0
    min_depth_to_fuse: 0.3
    #Multi-drone
    track_remote_netvlad_thres: 0.5
    #Initialization
    init_method: 0 #0 IMU, 1 PnP
    depth_estimate_baseline: 0.045
    #sliding window
    max_sld_win_size: 11
    landmark_estimate_tracks: 3 #when use depth or stereo, 3 is OK.
    min_solve_frames: 8
    #solver
    multiple_thread: 1
    #outlier rejection
    thres_outlier : 50.0
    perform_outlier_rejection_num: 50
    tri_max_err: 0.03
    #Marginalization
    enable_marginalization: 1
    margin_sparse_solver: 0
    always_fixed_first_pose: 0
    remove_base_when_margin_remote: 2
    #feature tracker parameters
    max_cnt: 200            # max feature number in feature tracking
    max_superpoint_cnt: 145 # max feature extraction by superpoint
    max_solve_cnt: 100
    show_track_id: 0
    check_essential: 0
    enable_lk_optical_flow: 0 #enable lk opticalflow featuretrack to enhance ego-motion estimation.
    lk_use_fast: 1
    remote_min_match_num: 40
    ransacReprojThreshold: 5.0
    parallex_thres: 0.012
    knn_match_ratio: 0.9 #This apply to superpoint feature track & loop clouse detection.
    feature_min_dist: 15
    enable_search_local_aera: true
    search_local_max_dist: 0.06
    #CNN
    cnn_use_onnx: 1
    enable_pca_superpoint: 1
    enable_pca_netvlad: 1
    superpoint_pca_dims: 64
    netvlad_pca_dims: 1024
    cnn_enable_tensorrt: 1
    cnn_enable_tensorrt_fp16: 1
    cnn_enable_tensorrt_int8: 1
    netvlad_int8_calib_table_name: "mobilenetvlad_calibration.flatbuffers"
    superpoint_int8_calib_table_name: "superpoint_calibration.flatbuffers"
    #Measurement parameters       The more accurate parameters you provide, the better performance
    acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
    gyr_n: 0.05         # gyroscope measurement noise standard deviation.     #0.05  0.004
    acc_w: 0.002         # accelerometer bias random work noise standard deviation.  #0.002
    gyr_w: 0.0004       # gyroscope bias random work noise standard deviation.     #4.0e-5
    g_norm: 9.805         # gravity magnitude
    #Loop Closure Detection
    loop_detection_netvlad_thres: 0.85
    enable_homography_test: 0
    loop_inlier_feature_num: 20
    accept_loop_max_yaw: 10
    accept_loop_max_pos: 1.0
    lazy_broadcast_keyframe: 0 #If enable coarse-to-fine initialization mode. This is useful when communication is not good.
    gravity_check_thres: 0.06
    #PGO
    pgo_mode: 0
    pgo_rho_frame_T: 0.7
    pgo_rho_frame_theta: 0.625
    pgo_eta_k: 0.1
    write_g2o: 0
    g2o_output_path: "output.g2o"
    write_pgo_to_file: 1
    enable_gravity_prior: 0
    gravity_sqrt_info: 10
    pgo_solver_time: 1.0
    solver_timer_freq: 1.0
    enable_pcm: 1
    pcm_thres: 2.8
    #outputs
    output_path: "/home/initial/swarm_log_latest"
    debug_print_sldwin: 0
    debug_print_states: 0
    enable_perf_output: 0
    debug_write_margin_matrix: 0
    print_network_status: 0
    verbose: 0
grid_map:
    frame_id: "world"
    depth_calib: "../../camera/d435_realsense/left_480x270.yaml"
    enable_virtual_wall: 0
    pose_type: 2
    odom_depth_timeout: 1.0
    resolution: 0.2
    local_update_range_x: 15.5
    local_update_range_y: 15.5
    local_update_range_z: 2.0
    obstacles_inflation: 0.1
    virtual_ceil: 3.0
    virtual_ground: -0.1
    use_depth_filter: 1
    depth_filter_tolerance: 0.15
    depth_filter_maxdist: 15.0
    depth_filter_mindist: 0.1
    depth_filter_margin: 2
    k_depth_scaling_factor: 1000
    est_depth_scaling_factor: 1
    inverse_depth: 0
    skip_pixel: 2
    p_hit: 0.65
    p_miss: 0.35
    p_min: 0.12
    p_max: 0.90
    p_occ: 0.80
    fading_time: 10
    occ_interval: 0.032
    vis_interval: 0.125
    min_ray_length: 0.1
    max_ray_length: 4.5
    visualization_truncate_height: 1.9
    show_occ_time: 0
fsm:
    flight_type: 1
    thresh_replan_time: 1.0
    planning_horizon: 5.0
    emergency_time: 1.0
    realworld_experiment: 0
    fail_safe: 1
    ground_height_measurement: 0
manager: 
    max_vel: 1.5
    max_acc: 6.0
    polyTraj_piece_length: 1.5
    feasibility_tolerance: 0.05
    planning_horizon: 7.5
    use_multitopology_trajs: 0
optimization:
    constraint_points_perPiece: 5
    weight_obstacle: 10000.0
    weight_obstacle_soft: 5000.0
    weight_swarm: 10000.0
    weight_feasibility: 10000.0
    weight_sqrvariance: 10000.0
    weight_time: 10.0
    obstacle_clearance: 0.1
    obstacle_clearance_soft: 0.5
    swarm_clearance: 0.15000000000000002
    max_vel: 1.5
    max_acc: 6.0
    max_jer: 20.0